services:

  payment-db:
    image: postgres:16
    container_name: payment-db
    environment:
      POSTGRES_DB: payflow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - payflow-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"   # Management UI
    networks:
      - payflow-network

  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "4000:4000"
    depends_on:
      - payment-db
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://payment-db:5432/payflow
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_RABBITMQ_HOST: rabbitmq
    networks:
      - payflow-network

  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "4001:4001"
    depends_on:
      - rabbitmq
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
    networks:
      - payflow-network

volumes:
  postgres-data:

networks:
  payflow-network:
    driver: bridge
