spring.application.name=payment-service




#spring.h2.console.path=/h2-console
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driver-class-name=org.h2.Driver



#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

#spring.jpa.hibernate.ddl-auto=update
#spring.sq.init.mode=always
#postgres.user=admin
#postgres.password=password
#postgres.db=db
#spring.datasource.username=admin



server.port=4000

logging.level.root=info

spring.datasource.url=jdbc:postgresql://payment-db:5432/payflow
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

